# This is just an example, use this docker compose just for test environment
services:
  duplicati-prometheus-exporter:
    build:
      context: .
    container_name: duplicati-prometheus-exporter
    image: duplicati-prometheus-exporter
    ports:
      - "5000:5000"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports: 
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
  grafana_monitoring:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  grafana-config:
    image: alpine
    depends_on:
      - grafana_monitoring
      - duplicati-prometheus-exporter
    volumes:
      - ./config:/config
    command: >
      /bin/sh -c "
        apk add --no-cache curl
        echo 'waiting for grafana'
        sleep 15s
        echo 'ADD DATASOURCE'
        curl --request POST http://grafana_monitoring:3000/api/datasources --header 'Content-Type: application/json' -d @/config/grafana/datasource.json
        echo 'ADD DASHBOARD'
        curl --request POST http://grafana_monitoring:3000/api/dashboards/import --header 'Content-Type: application/json' -d @/config/grafana/dashboard.json
        echo 'SEND BACKUP DEMO'
        curl --request POST http://duplicati-prometheus-exporter:5000 --header 'Content-Type: application/json' -d @/config/duplicati/duplicati-post-example.json
        "